### ISSUE TITLE
Awesome Flutter

### ISSUE THREAD

**Issue by Solido** [aeyrium/aeyrium-sensor#1]
Awesome-Flutter is the main curated resources list for Flutter
Would you like to join ? 
Thank you.

https://github.com/Solido/awesome-flutter

**Comment by diegoveloper** [comment]
Sure, what do we need?

**Comment by Solido** [comment]
You can PR so your name is added to the contributors list and I'll merge it

**Comment by diegoveloper** [comment]
@Solido PR sent!
