### ISSUE TITLE
sensor or listener is null

### ISSUE THREAD

**Issue by Liliana99** [aeyrium/aeyrium-sensor#5]
Hi,

I've copied the example  , then  at the moment to run shows nothing on device!!

on my debug console says : E/SensorManager( 2627): sensor or listener is null

Can you help me with this, please?

**Comment by diegoveloper** [comment]
Hello, probably your device doesn't have rotation sensor. What device do you have?

**Comment by Liliana99** [comment]
Hi, is  a samsumg tablet

**Comment by diegoveloper** [comment]
try using a phone . Do you know the model of the tablet? model/android version/  , give us more detail please.

**Comment by Liliana99** [comment]
ok, I'll  try on a phone,

The  tablet is Galaxy Tab A(2016) 
model   :  SM-T580
Version Android 8.1.0

**Comment by diegoveloper** [comment]
it's look like it doesn't have a rotation sensor https://www.sammobile.com/devices/galaxy-tab-a-2016-101-wi-fi/specs/SM-T580/

**Comment by Liliana99** [comment]
OK, thanks, 

Sorry I had check that before!!, I will try on a phone...

Thanks again.

**Comment by Falguni1441** [comment]
I have the same issue, it shows sensor or listener is null
Mobile : Moto e7 plus
Model : XT2081-2
Android version : 10

**Comment by SpicierEwe** [comment]
> I have the same issue, it shows sensor or listener is null Mobile : Moto e7 plus Model : XT2081-2 Android version : 10

did u find a solution? can u please tell me how can we check if a device supports a particular sensor  in flutter ? i could'nt find it anywhere
